//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShopYP02
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookShopEntities1 : DbContext
    {
        public BookShopEntities1()
            : base("name=BookShopEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Адреса> Адреса { get; set; }
        public virtual DbSet<ДеталиЗаказа> ДеталиЗаказа { get; set; }
        public virtual DbSet<Должности> Должности { get; set; }
        public virtual DbSet<Заказы> Заказы { get; set; }
        public virtual DbSet<КатегорииТоваров> КатегорииТоваров { get; set; }
        public virtual DbSet<ПаспортныеДанные> ПаспортныеДанные { get; set; }
        public virtual DbSet<Покупатели> Покупатели { get; set; }
        public virtual DbSet<Производители> Производители { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<СтатусыЗаказов> СтатусыЗаказов { get; set; }
        public virtual DbSet<Товары> Товары { get; set; }
    }
}
