//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShopYP02
{
    using System;
    using System.Collections.Generic;
    
    public partial class ДеталиЗаказа
    {
        public int КодДеталиЗаказа { get; set; }
        public Nullable<int> КодЗаказа { get; set; }
        public Nullable<int> КодТовара { get; set; }
        public int Количество { get; set; }
        public double Цена { get; set; }
    
        public virtual Заказы Заказы { get; set; }
        public virtual Товары Товары { get; set; }
    }
}
