//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShopYP02
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказы()
        {
            this.ДеталиЗаказа = new HashSet<ДеталиЗаказа>();
        }
    
        public int Код { get; set; }
        public Nullable<int> КодСотрудника { get; set; }
        public Nullable<int> КодПокупателя { get; set; }
        public System.DateTime ДатаОформления { get; set; }
        public Nullable<System.DateTime> ДатаДоставки { get; set; }
        public Nullable<int> КодАдреса { get; set; }
        public double СуммаЗаказа { get; set; }
        public Nullable<int> КодСтатусаЗаказа { get; set; }
    
        public virtual Адреса Адреса { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ДеталиЗаказа> ДеталиЗаказа { get; set; }
        public virtual Покупатели Покупатели { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual СтатусыЗаказов СтатусыЗаказов { get; set; }
    }
}
