//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShopYP02
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товары
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товары()
        {
            this.ДеталиЗаказа = new HashSet<ДеталиЗаказа>();
        }
    
        public int Id { get; set; }
        public string Автор { get; set; }
        public string Наименование { get; set; }
        public double Цена { get; set; }
        public Nullable<int> КодКатегории { get; set; }
        public string Картинка { get; set; }
        public string Описание { get; set; }
        public Nullable<double> РазмерСкидки { get; set; }
        public Nullable<int> КодПроизводителя { get; set; }
        public int Количество { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ДеталиЗаказа> ДеталиЗаказа { get; set; }
        public virtual КатегорииТоваров КатегорииТоваров { get; set; }
        public virtual Производители Производители { get; set; }
    }
}
